language: python
addons:
    firefox: "45.4.0esr"
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git@22c1b2f173919bef22f2d9d9295ec5396d02dffd#egg=xblock-sdk"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt"
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "mkdir var"
    - "wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz"
    - "mkdir geckodriver"
    - "tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver"
    - "export PATH=$PATH:$PWD/geckodriver"
script:
    - pep8 xblockutils --max-line-length=120
    - pylint xblockutils
    - python run_tests.py --with-coverage --cover-package=xblockutils
notifications:
  email: false
branches:
    only:
        - master
